import { isEnumValue } from '@gamepark/rules-api'

export enum Crew {
  PoulpirateBlueCrew1 = 1,
  PoulpirateBlueCrew2,
  PoulpirateBlueCrew3,
  PoulpirateGreenCrew1,
  PoulpirateGreenCrew2,
  PoulpirateGreenCrew3,
  PoulpirateBrownCrew1,
  PoulpirateBrownCrew2,
  PoulpirateBrownCrew3,
  PoulpiratePurpleCrew1,
  PoulpiratePurpleCrew2,
  PoulpiratePurpleCrew3,
  PoulpirateRedCrew1,
  PoulpirateRedCrew2,
  PoulpirateRedCrew3,
  PoulpirateGold4,
  PoulpirateGold6 ,
  ChamouraiBlueCrew1 = 100,
  ChamouraiBlueCrew2,
  ChamouraiBlueCrew3,
  ChamouraiGreenCrew1,
  ChamouraiGreenCrew2,
  ChamouraiGreenCrew3,
  ChamouraiBrownCrew1,
  ChamouraiBrownCrew2,
  ChamouraiBrownCrew3,
  ChamouraiPurpleCrew1,
  ChamouraiPurpleCrew2,
  ChamouraiPurpleCrew3,
  ChamouraiRedCrew1,
  ChamouraiRedCrew2,
  ChamouraiRedCrew3,
  ChamouraiGold4,
  ChamouraiGold6 ,
}

export const poulpirateCrews = Object.values(Crew).filter(isEnumValue).filter((c) => c < Crew.ChamouraiBlueCrew1)
export const chamouraiCrews = Object.values(Crew).filter(isEnumValue).filter((c) => c >= Crew.ChamouraiBlueCrew1)

export const PoulpirateDeck = {
  [Crew.PoulpirateBlueCrew1]: 3,
  [Crew.PoulpirateBlueCrew2]: 2,
  [Crew.PoulpirateBlueCrew3]: 1,
  [Crew.PoulpirateGreenCrew1]: 3,
  [Crew.PoulpirateGreenCrew2]: 2,
  [Crew.PoulpirateGreenCrew3]: 1,
  [Crew.PoulpirateBrownCrew1]: 3,
  [Crew.PoulpirateBrownCrew2]: 2,
  [Crew.PoulpirateBrownCrew3]: 1,
  [Crew.PoulpiratePurpleCrew1]: 3,
  [Crew.PoulpiratePurpleCrew2]: 2,
  [Crew.PoulpiratePurpleCrew3]: 1,
  [Crew.PoulpirateRedCrew1]: 3,
  [Crew.PoulpirateRedCrew2]: 2,
  [Crew.PoulpirateRedCrew3]: 1,
  [Crew.PoulpirateGold4]: 5,
  [Crew.PoulpirateGold6]: 1
}
export const ChamouraiDeck = {
  [Crew.ChamouraiBlueCrew1]: 3,
  [Crew.ChamouraiBlueCrew2]: 2,
  [Crew.ChamouraiBlueCrew3]: 1,
  [Crew.ChamouraiGreenCrew1]: 3,
  [Crew.ChamouraiGreenCrew2]: 2,
  [Crew.ChamouraiGreenCrew3]: 1,
  [Crew.ChamouraiBrownCrew1]: 3,
  [Crew.ChamouraiBrownCrew2]: 2,
  [Crew.ChamouraiBrownCrew3]: 1,
  [Crew.ChamouraiPurpleCrew1]: 3,
  [Crew.ChamouraiPurpleCrew2]: 2,
  [Crew.ChamouraiPurpleCrew3]: 1,
  [Crew.ChamouraiRedCrew1]: 3,
  [Crew.ChamouraiRedCrew2]: 2,
  [Crew.ChamouraiRedCrew3]: 1,
  [Crew.ChamouraiGold4]: 5,
  [Crew.ChamouraiGold6]: 1
}